version: 2

models:
  - name: gold_fct_games
    description: "The central fact table for the baseball star schema, combining all game-related metrics and foreign keys for analysis."
    columns:
      - name: game_id
        description: "The unique identifier for a game. Serves as the primary key for the fact table."
        tests:
          - unique
          - not_null

      - name: home_team_id
        description: "Foreign key to the teams dimension for the home team."
        tests:
          - not_null
          - relationships:
              to: ref('gold_dim_teams')
              field: team_id

      - name: away_team_id
        description: "Foreign key to the teams dimension for the away team."
        tests:
          - not_null
          - relationships:
              to: ref('gold_dim_teams')
              field: team_id

      - name: venue_id
        description: "Foreign key to the venues dimension."
        tests:
          - not_null
          - relationships:
              to: ref('gold_dim_venues')
              field: venue_id

      - name: game_date
        description: "The date the game was played."
      - name: year
        description: "The year the game was played."
      - name: type
        description: "The type of game (e.g., regular season, postseason)."
      - name: day_night
        description: "Indicates if the game was played during the day or at night."

      - name: attendance
        description: "The official game attendance."
        tests:
          - not_null
      - name: home_runs
        description: "The number of runs scored by the home team."
        tests:
          - not_null
      - name: away_runs
        description: "The number of runs scored by the visiting team."
        tests:
          - not_null
      - name: duration_minutes
        description: "The total duration of the game in minutes."
        tests:
          - not_null

  - name: gold_dim_teams
    description: "Dimension table for baseball teams, containing a unique record for each team."
    columns:
      - name: team_id
        description: "The unique identifier for a team. Serves as the primary key."
        tests:
          - unique
          - not_null
      - name: team_name
        description: "The full name of the team."

  - name: gold_dim_venues
    description: "Dimension table containing descriptive information about each game venue."
    columns:
      - name: venue_id
        description: "The unique identifier of the venue. Serves as the primary key."
        tests:
          - unique
          - not_null
      - name: venue_name
        description: "The name of the venue."
      - name: venue_capacity
        description: "The maximum seating capacity of the venue."
      - name: venue_street
        description: "The street address of the venue."
      - name: venue_state
        description: "The state where the venue is located."
      - name: venue_zipcode
        description: "The postal code of the venue."

  - name: gold_dim_players
    description: "Dimension table for players, containing one unique row per player based on their most recent game data."
    columns:
      - name: player_id
        description: "The unique identifier for each player. Serves as the primary key."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "The first name of the player."
      - name: last_name
        description: "The last name of the player."
      - name: hitter
        description: "Flag to indicate if the player is a hitter."
      - name: hitter_weight
        description: "The weight of the hitter."
      - name: hitter_height
        description: "The height of the hitter."
      - name: hitter_bat_hand
        description: "The hand the player bats with (L/R/B or U for unknown)."
        tests:
          - accepted_values:
              values: ['L', 'R', 'B', 'U']
      - name: pitcher_hand
        description: "The hand the player pitches with (L/R or U for unknown)."
        tests:
          - accepted_values:
              values: ['L', 'R', 'U']
      - name: pitch_type
        description: "The type of pitch."