substitutions:
  _DBT_FLAGS: "" # Default value is an empty string

steps:
  # Use dbt's official BigQuery image so dependencies are preinstalled
  - name: 'ghcr.io/dbt-labs/dbt-bigquery:1.8.6'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        set -euo pipefail
        dbt --version
        # Use a dedicated CI target (recommended) or adjust to your target name
        dbt debug --profiles-dir . --target ci
        dbt build $_DBT_FLAGS --profiles-dir . --target ci

options:
  logging: CLOUD_LOGGING_ONLY
