substitutions:
  _DBT_FLAGS: "" # Default value is an empty string

steps:
  # Use a single Python-based step and install dbt-bigquery via pip to avoid GHCR pulls
  - name: 'python:3.11'
    entrypoint: 'bash'
    env:
      - "PROJECT_ID=$PROJECT_ID"
    args:
      - -lc
      - |
        set -euo pipefail
        python --version
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir 'dbt-bigquery~=1.8'
        dbt --version
        dbt debug --profiles-dir . --target ci
        dbt build $_DBT_FLAGS --profiles-dir . --target ci

options:
  logging: CLOUD_LOGGING_ONLY
