substitutions:
  _DBT_FLAGS: "" # Default value is an empty string

steps:
  # Upgrade pip
  - name: 'python:3.9'
    entrypoint: python
    args: [ '-m', 'pip', 'install', '--upgrade', 'pip' ]

  # Install dbt and its requirements
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  # Run the dbt commands
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - -c
      - |
        dbt debug --target dev && dbt build $_DBT_FLAGS --profiles-dir . --target dev      

options:
  logging: CLOUD_LOGGING_ONLY